# Generated by Django 4.0.2 on 2024-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_alter_barcodescan_scan_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodescan',
            options={'ordering': ['time_taken']},
        ),
        migrations.AddIndex(
            model_name='barcodescan',
            index=models.Index(fields=['time_taken'], name='Events_barc_time_ta_f13b68_idx'),
        ),
    ]
