# Generated by Django 4.2 on 2025-02-04 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0004_alter_aboutsection_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the race, including any special requirements or instructions",
                null=True,
                verbose_name="Race Description",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the distance to be covered (in kilometers)",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Race Distance (km)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="number_of_obstacles",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Enter the total number of obstacles in the race (if applicable)",
                null=True,
                verbose_name="Number of Obstacles",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="terrain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROAD", "Road"),
                    ("TRAIL", "Trail"),
                    ("MIXED", "Mixed Terrain"),
                    ("TRACK", "Track"),
                    ("CROSS", "Cross Country"),
                ],
                help_text="Select the primary terrain type for the race",
                max_length=20,
                null=True,
                verbose_name="Terrain Type",
            ),
        ),
    ]
