name: Django CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Event-Management
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            pip install gunicorn
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl daemon-reload
            sudo systemctl restart cicdapp.service
            sudo systemctl status cicdapp.service
