name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script_stop: true
          timeout: 60s
          command_timeout: 20m
          script: |
            cd /home/ubuntu/Event-Management
            git pull origin main
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install/upgrade dependencies
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # Run migrations
            python manage.py makemigrations
            python manage.py migrate
            
            # Collect static files
            python manage.py collectstatic --noinput
            
            # Create superuser using environment variables
            if [ ! -f ".superuser_created" ]; then
              echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('${{ secrets.DJANGO_SUPERUSER_USERNAME }}', '${{ secrets.DJANGO_SUPERUSER_EMAIL }}', '${{ secrets.DJANGO_SUPERUSER_PASSWORD }}')" | python manage.py shell
              touch .superuser_created
            fi
            
            # Restart the service
            sudo systemctl daemon-reload
            sudo systemctl restart Event-Management.service
